version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: poetgres
      POSTGRES_PASSWORD: poetgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .\smart_home\init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "poetgres"] 
      interval: 10s
      timeout: 5s  # Added timeout for healthcheck
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - smarthome-network

  ## тут нужно добавить приложение

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://poetgres:poetgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8181
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network
  temperature-api:
    build:
      context: ./temperature_detector
    container_name: temperature-api
    ports:
      - "8181:8181"
    restart: unless-stopped
    networks:
      - smarthome-network
volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge